/**
 *  This file was auto generated, please do not edit it directly.
**/

package domaintype

type EFx struct {
}

func NewEFx() *EFx {
	return &EFx{}
}

type EFxModuleType struct {
	Id                    string
	Slug                  string
	Name                  string
	Description           string
	IsAccessControl       bool
	IsGuestManagement     bool
	IsConcierge           bool
	IsAthleteBag          bool
	IsDigitalMemoryBank   bool
	IsGuestInfo           bool
	IsMessaging           bool
	IsProductPickup       bool
	IsRaffle              bool
	IsReservation         bool
	IsRoamingPhotographer bool
	IsSmartBar            bool
	IsSmsQuiz             bool
	IsTeams               bool
	IsLeadRetrieval       bool
	IsAdminOnly           bool
	IconURL               string
	DependencyNFC         bool
	DependencySMS         bool
	CompatibilityNFC      bool
	CompatibilitySMS      bool
}

type EFxScreenType struct {
	Slug                  string
	Name                  string
	Description           string
	IsScanView            bool
	IsFailureView         bool
	IsCheckOutView        bool
	IsSuccessView         bool
	IsRegisterSuccessView bool
	IsRegisterScanView    bool
	IsRegisterFailureView bool
}

type EFxStationType struct {
	Slug         string
	Name         string
	Description  string
	IsCheckIn    bool
	IsCheckInOut bool
}

func (f *EFx) ListEFxModuleTypes() []EFxModuleType {
	return []EFxModuleType{
		{
			Id:                    `Activation`,
			Slug:                  `guest-management`,
			Name:                  `Guest Management`,
			Description:           `Activate a user in EFx via QR or NFC`,
			IsAccessControl:       false,
			IsGuestManagement:     true,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/guest-management.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `AccessControl`,
			Slug:                  `access-control`,
			Name:                  `Access Control`,
			Description:           `Scan assets to grant access to exclusive event experiences`,
			IsAccessControl:       true,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/access.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `AthleteBag`,
			Slug:                  `athletes-bag`,
			Name:                  `Athletes Bag`,
			Description:           `Custom module for Nike`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          true,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           true,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/nike.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `Concierge`,
			Slug:                  `concierge`,
			Name:                  `Concierge`,
			Description:           `Deliver key information to attendees when they scan assets at kiosk`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           true,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/concierge.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `DigitalMemoryBank`,
			Slug:                  `digital-memory-bank`,
			Name:                  `Digital Memory Bank`,
			Description:           `Create and share a personalized post-event content hub with your attendees`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   true,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/digital-memory-bank.png`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `GuestInfo`,
			Slug:                  `guest-info`,
			Name:                  `Guest Info`,
			Description:           `Custom diagnostic tool`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           true,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           true,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/access.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `Messaging`,
			Slug:                  `messaging`,
			Name:                  `Messaging`,
			Description:           `Engage attendees via SMS messaging`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           true,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/messaging.png`,
			DependencyNFC:         false,
			DependencySMS:         true,
			CompatibilityNFC:      false,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `SMSQuiz`,
			Slug:                  `smsquiz`,
			Name:                  `Poll`,
			Description:           `Text guests via SMS. View responses in EFx mobile app and Apple TV app`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             true,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/polling.png`,
			DependencyNFC:         false,
			DependencySMS:         true,
			CompatibilityNFC:      false,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `ProductPickup`,
			Slug:                  `product-pickup`,
			Name:                  `Product Pickup`,
			Description:           `Scan asset to confirm attendees&#039; eligibility to receive or purchase products`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       true,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/product-pickup.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Raffle`,
			Slug:                  `raffle`,
			Name:                  `Raffle`,
			Description:           `Select prize winners and notify them via SMS`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              true,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/raffle.png`,
			DependencyNFC:         true,
			DependencySMS:         true,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Reservation`,
			Slug:                  `reservation`,
			Name:                  `Reservation`,
			Description:           `Queue attendees in a virtual line and notify them via SMS when availability opens`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         true,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/reservation.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `RoamingPhotographer`,
			Slug:                  `roaming-photographer`,
			Name:                  `Roaming Photographer`,
			Description:           `Take photo and apply custom event filters. Deliver images via SMS`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: true,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/photographer.png`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `SmartBar`,
			Slug:                  `smart-bar`,
			Name:                  `Smart Bar`,
			Description:           `Attendees scan assets at bar kiosks to place orders in bartender queue`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            true,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/smartbar-vertical.png`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `Teams`,
			Slug:                  `teams`,
			Name:                  `Teams`,
			Description:           `Build attendee teams for competition, collaboration, and networking; track scores on the leaderboard`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               true,
			IsLeadRetrieval:       false,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/teams.png`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      false,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `LeadRetrieval`,
			Slug:                  `lead-retrieval`,
			Name:                  `Lead Retrieval`,
			Description:           `Get leads for your events`,
			IsAccessControl:       false,
			IsGuestManagement:     false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsLeadRetrieval:       true,
			IsAdminOnly:           false,
			IconURL:               `https://cdn.eventfarm.com/platform/img/icons/lead-retrieval.png`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
	}
}

func (f *EFx) ListEFxScreenTypes() []EFxScreenType {
	return []EFxScreenType{
		{
			Slug:                  `scan-view`,
			Name:                  `Scan View`,
			Description:           ``,
			IsScanView:            true,
			IsFailureView:         false,
			IsCheckOutView:        false,
			IsSuccessView:         false,
			IsRegisterSuccessView: false,
			IsRegisterScanView:    false,
			IsRegisterFailureView: false,
		},
		{
			Slug:                  `failure-view`,
			Name:                  `Failure View`,
			Description:           ``,
			IsScanView:            false,
			IsFailureView:         true,
			IsCheckOutView:        false,
			IsSuccessView:         false,
			IsRegisterSuccessView: false,
			IsRegisterScanView:    false,
			IsRegisterFailureView: false,
		},
		{
			Slug:                  `check-out-view`,
			Name:                  `Check Out View`,
			Description:           ``,
			IsScanView:            false,
			IsFailureView:         false,
			IsCheckOutView:        true,
			IsSuccessView:         false,
			IsRegisterSuccessView: false,
			IsRegisterScanView:    false,
			IsRegisterFailureView: false,
		},
		{
			Slug:                  `success-view`,
			Name:                  `Success View`,
			Description:           ``,
			IsScanView:            false,
			IsFailureView:         false,
			IsCheckOutView:        false,
			IsSuccessView:         true,
			IsRegisterSuccessView: false,
			IsRegisterScanView:    false,
			IsRegisterFailureView: false,
		},
		{
			Slug:                  `register-success-view`,
			Name:                  `Register Success View`,
			Description:           ``,
			IsScanView:            false,
			IsFailureView:         false,
			IsCheckOutView:        false,
			IsSuccessView:         false,
			IsRegisterSuccessView: true,
			IsRegisterScanView:    false,
			IsRegisterFailureView: false,
		},
		{
			Slug:                  `register-scan-view`,
			Name:                  `Register Scan View`,
			Description:           ``,
			IsScanView:            false,
			IsFailureView:         false,
			IsCheckOutView:        false,
			IsSuccessView:         false,
			IsRegisterSuccessView: false,
			IsRegisterScanView:    true,
			IsRegisterFailureView: false,
		},
		{
			Slug:                  `register-failure-view`,
			Name:                  `Register Failure View`,
			Description:           ``,
			IsScanView:            false,
			IsFailureView:         false,
			IsCheckOutView:        false,
			IsSuccessView:         false,
			IsRegisterSuccessView: false,
			IsRegisterScanView:    false,
			IsRegisterFailureView: true,
		},
	}
}

func (f *EFx) ListEFxStationTypes() []EFxStationType {
	return []EFxStationType{
		{
			Slug:         `check-in`,
			Name:         `CheckIn`,
			Description:  ``,
			IsCheckIn:    true,
			IsCheckInOut: false,
		},
		{
			Slug:         `check-in-out`,
			Name:         `CheckInOut`,
			Description:  ``,
			IsCheckIn:    false,
			IsCheckInOut: true,
		},
	}
}
